### ISSUE TITLE
Inconsistency in orthosnap results

### ISSUE THREAD

**Issue by yuemeanshappy** [JLSteenwyk/orthosnap#3]
Hi Jacob,

I used orthosnap (0.1.1) to identify SNAP-OGs from a group of orthogroups, but found that the results sometimes are not reproducible in some orthogroups, like the one (OG0010358.fa) I provided here.

The command line I used was `orthosnap -f OG0010358.fa -t OG0010358.fa.contree -op ./results` and it identified one SNAP-OG each time. But the SNAP-OG identified in the first round (`first-round-OG0010358.fa.orthosnap.0.fa`)was different from the one identified in the second round (`second-round-OG0010358.fa.orthosnap.0.fa`).  All files attached at the end. (The `.fa` and `.contree` are not supported by GitHub, so I stored them in `.txt` to upload.)

Before running orthosnap, I used OrthoFinder to identify orthogroups, used MAFFT and ClipKit to trim the alignment, and used IQ-Tree to build the gene tree.

Any thoughts are much appreciated!

Best,
Yue

[first-round-OG0010358.fa.orthosnap.0.fa.txt](https://github.com/JLSteenwyk/orthosnap/files/11390083/first-round-OG0010358.fa.orthosnap.0.fa.txt)
[OG0010358.fa.contree.txt](https://github.com/JLSteenwyk/orthosnap/files/11390086/OG0010358.fa.contree.txt)
[OG0010358.fa.txt](https://github.com/JLSteenwyk/orthosnap/files/11390087/OG0010358.fa.txt)
[second-round-OG0010358.fa.orthosnap.0.fa.txt](https://github.com/JLSteenwyk/orthosnap/files/11390089/second-round-OG0010358.fa.orthosnap.0.fa.txt)

**Comment by JLSteenwyk** [comment]
Hi Yue,

Thank you for writing and providing the necessary information, such as the software version and data files.

I ran OrthoSNAP 10 times on the data and got the same output each time. I'm sorry, but I am unable to recapitulate your issue. Perhaps there is some issue with version controls. If you haven't, I recommend installing OrthoSNAP into a virtual environment.

Please let me know if the issue persists, otherwise I will wait a few days before closing the issue.

All the best,

Jacob

**Comment by yuemeanshappy** [comment]
Hi Jacob,

Thank you so much for your quick response! I figure it out. The issue does not persist.

Thanks again,
Yue

**Comment by JLSteenwyk** [comment]
Great - happy to hear it!
